export const FETCH_SURVEY_SUCESS = 'FETCH_SURVEY_SUCESS';
export const FETCH_SURVEY_FAIL = 'FETCH_SURVEY_FAIL';
export const FETCH_SURVEY_FETCH_START = 'FETCH_SURVEY_FETCH_START';
export const GO_TO_NEXT_QUETION = 'GO_TO_NEXT_QUETION';
export const GO_TO_PREVIOUS_QUETION = 'GO_TO_PREVIOUS_QUETION';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
